parameters:
    da_api_server.security.authentication.provider.api.class: Da\ApiServerBundle\Security\Authentication\Provider\ApiAuthProvider
    da_api_server.security.authentication.listener.api.class: Da\ApiServerBundle\Security\Firewall\ApiAuthListener
    da_api_server.security.authentication.provider.oauth.class: Da\ApiServerBundle\Security\Authentication\Provider\OAuthProvider
    da_api_server.security.authentication.listener.oauth.class: Da\ApiServerBundle\Security\Firewall\OAuthListener
    da_api_server.client_manager.http.class: Da\ApiServerBundle\HttpClient\ClientManager
    da_api_server.user_manager.http.class: Da\ApiServerBundle\HttpClient\UserManager
    da_api_server.event.api_listener.class: Da\ApiServerBundle\Event\ApiListener
    da_api_server.client.class: Da\AuthCommonBundle\Model\Client
    da_api_server.user.class: Da\AuthCommonBundle\Model\User

services:
    da_api_server.security.authentication.provider.api:
        class: %da_api_server.security.authentication.provider.api.class%
        public: false
        arguments: [null, null]

    da_api_server.security.authentication.listener.api:
        class: %da_api_server.security.authentication.listener.api.class% 
        public: false
        arguments: [@security.context, @security.authentication.manager]

    da_api_server.security.authentication.provider.oauth:
        class: %da_api_server.security.authentication.provider.oauth.class%
        public: false
        arguments: [null, null]

    da_api_server.security.authentication.listener.oauth:
        class: %da_api_server.security.authentication.listener.oauth.class% 
        public: false
        arguments: [@security.context, @security.authentication.manager]

    da_api_server.client_manager.http:
        class: %da_api_server.client_manager.http.class%
        arguments: [null, null, %da_api_server.client.class%]
        public: false
        lazy: true

    da_api_server.user_manager.http:
        class: %da_api_server.user_manager.http.class%
        arguments: [null, null, %da_api_server.user.class%]
        public: false
        lazy: true

    da_api_server.event.api_listener:
        class: %da_api_server.event.api_listener%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }